name: Moodle Plugin CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        branch: [MOODLE_405_STABLE, MOODLE_500_STABLE]
        php: ['8.2']

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer
          ini-values: |
            max_input_vars=5000
            post_max_size=256M
            upload_max_filesize=256M
            memory_limit=512M

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n --no-dev moodlehq/moodle-plugin-ci ci
          echo "$PWD/ci/bin" >> $GITHUB_PATH

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres && break
            sleep 2
          done

      - name: Install Moodle (skip test-suite init)
        env:
          PGHOST: 127.0.0.1
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          moodle-plugin-ci install \
            --plugin ./ \
            --db-type=pgsql \
            --db-host=127.0.0.1 \
            --db-port=5432 \
            --db-user=postgres \
            --db-pass=postgres \
            --db-name=moodle \
            --branch ${{ matrix.branch }} \
            --no-init

      - name: PHP Lint
        run: moodle-plugin-ci phplint local/cohortunenroller

      - name: Coding style (moodle-cs)
        run: moodle-plugin-ci phpcs --max-warnings=0 local/cohortunenroller
      - name: PHPUnit (auto-inits phpunit only)
        run: moodle-plugin-ci phpunit --fail-on-skipped

      # Behat absichtlich weggelassen

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.branch }}-php${{ matrix.php }}
          path: |
            workdir/*/moodledata/*.log
            workdir/*/moodle/error.log
            workdir/*/behat_faildump/**
          if-no-files-found: ignore